### ISSUE TITLE
Garden Installer for Linux, Windows etc

### ISSUE THREAD

**Issue by fthamura** [cloudfoundry/garden#54]
will the CF team create garden as bundle binary, installer for windows, mac or linux (ubuntu or redhat)

so the users can use it and test it.

rather using go bla bla bla.

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#141559661](https://www.pivotaltracker.com/story/show/141559661) Garden Installer for Linux, Windows etc


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by julz** [comment]
Hi @fthamura -

since garden itself is just an API each implementation for a particular platform chooses whether to release a bundle binary/installer. For garden's runC-based backend, which is used on linux platforms, you can grab an all-in-one binary (named `gdn`) from any release version in https://github.com/cloudfoundry/garden-runc-release/releases. For example the latest release as I write this is [`gdn 1.3.0`](https://github.com/cloudfoundry/garden-runc-release/releases/download/v1.3.0/gdn-1.3.0/), which is available at https://github.com/cloudfoundry/garden-runc-release/releases/download/v1.3.0/gdn-1.3.0/. 

Hope this helps!

**Comment by fthamura** [comment]
but it is just a relase

take a look this

https://docs.docker.com/engine/installation/linux/ubuntu/

why dont you go this direction?

**Comment by julz** [comment]
to be clear, the release contains an all-in-one binary which you can download. You just need to run `gdn server`. There's no need for an installer or anything else: the single binary sets everything up and runs the garden server. Garden is mainly intended to be used as a component in larger systems (like Cloud Foundry and Concourse) rather than directly by a user so we don't provide distribution packages, but the all-in-one binary should make it very easy to get started with garden on linux.
